import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/navbar/navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">            
      <body className={inter.className}>        
        <Navbar/>
        {children}
        <p className="text-sm font-light mt-10 mb-5 text-center">Made by 齐丹27 & Dapa</p> 
      </body>
    </html>
  );
}
